"""character and film models update with auto-generated created-updated timestamp

Revision ID: 6c2888ec20a9
Revises: f31ada145991
Create Date: 2025-09-02 20:51:23.953546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c2888ec20a9'
down_revision: Union[str, Sequence[str], None] = 'f31ada145991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'created',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('characters', 'edited',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint(None, 'characters', ['name'])
    op.alter_column('films', 'opening_crawl',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('films', 'director',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('films', 'producer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('films', 'created',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('films', 'edited',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint(None, 'films', ['title'])
    op.create_unique_constraint(None, 'starships', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'starships', type_='unique')
    op.drop_constraint(None, 'films', type_='unique')
    op.alter_column('films', 'edited',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('films', 'created',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('films', 'producer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('films', 'director',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('films', 'opening_crawl',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'characters', type_='unique')
    op.alter_column('characters', 'edited',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('characters', 'created',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
